#!/usr/bin/python

import argparse
import sys
from pymake import parser
import pdb

parse = argparse.ArgumentParser(description='Check Makefile style.')
parse.add_argument('makefiles', help='Makefile file names', nargs='*')
parse.add_argument('--targets', dest='targets', action='store',default=None, help='Comma-separated list of targets that must be present')

args = parse.parse_args()

targets = args.targets.split(',')

found_targets = []

for f in args.makefiles:
    fd = open(f, 'rU')
    s = fd.read()
    fd.close()
    stmts = parser.parsestring(s, f)
    for s in stmts:
        try:
            found_targets.append(s.targetexp.s)
        except AttributeError:
            pass

missing_targets = set(targets) - set(found_targets)

for i in list(missing_targets):
    print 'Error: Missing target %s'%i
